In [1]:
import numpy as np

# np.array()

In [23]:
data = np.array([[ 0.226, -0.23 , -0.86],
[ 0.5639, 0.2379, 0.904]])
data

array([[ 0.226 , -0.23  , -0.86  ],
       [ 0.5639,  0.2379,  0.904 ]])

建立一個ndarrays

In [31]:
data1 = [12,4.5,24,767,97]
arr1 = np.array(data1)
print(arr1)
data2 = [[12,4.5,23],[24,767,97]]
arr2 = np.array(data2)
print(arr2)

[ 12.    4.5  24.  767.   97. ]
[[ 12.    4.5  23. ]
 [ 24.  767.   97. ]]


.ndim 查看ndarrays有多少維

In [33]:
print(arr1.ndim)
print(arr2.ndim)

2
1


想看是幾乘幾的矩陣可以使用.shape

In [37]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


Type provide

In [4]:
data2 = np.array([1, 2, 3], dtype=complex)
data2

array([1.+0.j, 2.+0.j, 3.+0.j])

In [22]:
# 前面是位置，後面是資料型態:
x = np.array([(1.21,2),(3,4.2)],dtype=[('a','<f4'),('b','<i4')])
x['b']

array([2, 4])

Creat data

In [40]:
arr3 = np.arange(10)
print(arr3)
# 跟list一樣可以利用index查找
print(arr3[2])
print(arr3[2:6])

[0 1 2 3 4 5 6 7 8 9]
2
[2 3 4 5]


In [54]:
# Slicing    ndarrays可透過切割，再利用索引進行局部改變
arr4 = np.arange(10)
popo = arr4[3:6]
popo[1] = 433
print(arr4)

[  0   1   2   3 433   5   6   7   8   9]


# 廣播 

In [62]:
# 廣播的使用原來的向量而不需要實際的複製
arr5 = np.array([12,23,34])
print(arr5)
d = 2
yoyo = arr5 * d
print(yoyo)
# 相當於d也是一個array，可以想像是Numpy會把d給放大變成和arr5一樣的大小（shape），而不需要自己去複製和arr5一樣多個2。

[12 23 34]
[24 46 68]


In [74]:
x = np.array([0,1,2,3])
x2 = x.reshape(4,1)
print(x2)
y1 = np.ones(5)
print(y1)
zz = y1 + x2

[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
None


.base 判斷某array是基於哪個陣列延伸出 是會返回True 否會返回None

In [82]:
gg = np.arange(5)
hh = gg.reshape(5,1)
print(hh.base is gg)
ff = gg * 3
ff.base is gg

True


False

# Numpy的數學&統計方法！

Random Data

random.randn()這個是隨機數有可能為負、正的整、小數

In [88]:
a22 = np.random.randn(20,2) #20行的2維陣列
print(a22)
print(a22 + 10)

[[-1.40694060e+00 -1.23538959e+00]
 [ 3.92277724e-01 -5.12783367e-01]
 [ 3.94303752e-01 -4.66636440e-01]
 [-1.78297553e+00 -8.12016829e-01]
 [ 8.07097679e-02 -1.23251497e+00]
 [ 3.82685700e-01  2.03160941e+00]
 [ 1.14401533e+00  7.02607108e-01]
 [-7.65991939e-01 -1.64480120e-02]
 [ 9.65449088e-01 -4.33911415e-01]
 [-3.67352165e-01 -2.85785122e-01]
 [-1.31951689e+00  7.95132259e-01]
 [ 2.41050751e+00  3.70796189e-01]
 [ 2.70154526e-01 -2.26933518e+00]
 [ 1.10324985e+00 -5.76621827e-04]
 [ 1.16576953e+00 -4.57177523e-01]
 [ 2.17682161e+00 -4.62242324e-01]
 [-1.70210617e-01 -1.85542360e+00]
 [-9.03291322e-01  9.86929186e-01]
 [-2.76618395e-01 -7.89091663e-01]
 [ 7.86377763e-01 -1.06607578e+00]]
[[ 8.5930594   8.76461041]
 [10.39227772  9.48721663]
 [10.39430375  9.53336356]
 [ 8.21702447  9.18798317]
 [10.08070977  8.76748503]
 [10.3826857  12.03160941]
 [11.14401533 10.70260711]
 [ 9.23400806  9.98355199]
 [10.96544909  9.56608858]
 [ 9.63264784  9.71421488]
 [ 8.68048311 10.79513226]
 [

.random.randint(low, high=None, size=None, dtype='l') 隨機整數

In [197]:
i10 = np.random.randint(10,22,size=10)
print(i10)
i42 = np.random.randint(2,13,size=[4,2])
print(i42)
i_arr = np.random.randint([2,5],[6,8],size=[4,2])
print(i_arr)

[13 21 18 19 14 12 13 20 13 21]
[[ 8  9]
 [12 10]
 [ 7  9]
 [ 2  4]]
[[4 7]
 [4 7]
 [3 7]
 [5 7]]


.mean() 取平均值

In [214]:
i10 = np.random.randint(10,22,size=10)
i10.mean()

14.6

In [244]:
i20 = np.random.randint(10,None,size=10)
i20

array([7, 8, 3, 8, 8, 8, 0, 8, 1, 6])

In [ ]:
.sum(總和)

In [217]:
obj1 = [1,2,3,4,5]
np.array(obj1).sum()

15

In [228]:
# cumsum()會回傳累加
obj2 = np.array([[2,3,4], [5,6,7]])
print(obj2.cumsum(),'\n')
list1 = [2,3,4,5,6,7]
print(np.cumsum(list1))

[ 2  5  9 14 20 27] 

[ 2  5  9 14 20 27]


In [231]:
# .std() 表準差
obj3 = np.array([[1,2],[3,4]])
obj3.std()

1.118033988749895